# -*- coding: utf-8 -*-
"""LIST_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TpMwk8kX9NMms7y_Z4pxnAS7ccihzSN
"""

#Reversing a list
a=[2,'hi',-13,3+6j,True]
a.reverse()
a

a=[2,'hi',-13,3+6j,True]
a[::-1]

# Swapping of first and last element
b=[2,'hi',-13,3+6j,True]
b[0],b[4]=b[4],b[0]
b

c=[2,'hi',-13,3+6j,True]
c[0],c[-1]=c[-1],c[0]
c

#Max no in list
w=[2,5,-1,6.3,-44,23]
max=w[0]
for i in w:
  if i>max:
    max=i
print('max is',max)

#Min no in list
w=[2,5,-1,6.3,-44,23]
min=w[0]
for i in w:
  if i<min:
    min=i
print('min is',min)

# Sum no present in list
w=[2,5,-1,6.3,-44,23,27]
q=0
for i in w:
  q=i+q
print(q)

#Odd and even no in list
w=[2,5,1,23,34,27]
count_even=0
count_odd=0
for i in w:
  if i%2==0:
    count_even=count_even+1
    print('even',i)
  else:
    count_odd=count_odd+1
    print('odd',i)
print('count_even',count_even)
print('count_odd',count_odd)

# Common element in list
a=[22,4,1,56,3,18]
b=[21,33,4,14,1,9]
for i in a:
  for j in b:
    if i==j:
      print(i)
else:
  print('no common')

#Add more than 1 data in list
#METHOD 1

c=[2,5,1,4.2,-5,11,24]
b=[12,-8.4,5]
c.extend(b)
c

#Add more than 1 data in list
#METHOD 2

c=[2,5,1,4.2,24]
s=[3,9,-2]
for i in c:
  s.append(i)
print(s)

#Add more than 1 data in list
#METHOD 3

u=[2,5,1,7,-5,24]
e=[3,9,-2,19]
f=u+e
print(f)

