# -*- coding: utf-8 -*-
"""LIST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V3ySQvTIJVaXfMOSh-bgGRQjZnsVRzcT
"""

a=[2,4,1,9,-3,True,'false',4+2j,-1]

a

a[4]

print(a[1])

a[6]=12

a

b=[-2,8,5,0,-23,56,12,-78]

b.sort()   #sort==Arrange the elements in ascending order

b

c=[-2,8,5,0,-23,56,12,-78]
c.reverse()

c

c.append(23)

c

c.insert(5,-13)

c

c.pop(1)     #if index no not given then pop will remove last element

c.remove(56)

c

