# -*- coding: utf-8 -*-
"""Python L1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oCvm5sKu56xxQ_UEoXl_6pl2uqeHPfkA
"""

print('Hello world')

print("Good Morning",-3.6)

print('Hello \n and good morning')

print("Hello world")

name='Jjdjk'
frnd='kdlld'
another='slskq'
print('Hello '+frnd)

name[0]

name[1]

name[2]

name[3]

name[4]

for i in name:
  print(i)

name='ajay,dev'
print(name[0:10])

len(name)

nm='ramdev'
nm[-4:-2]

nme='himanshu'
nme.upper()

name1='HIMANSHU'
name1.lower()

nam2='jsjosjoj!!!'
nam2.rstrip('!')

nam2='jsjosjoj!!!'
nam2.replace('jsjosjoj','steve')

nm3='hjjo 88jjjqqjjsojokp j1k2lljl3l'
nm3.split()

# CODE W/O MATCH CASE STATEMENT
mood='thristy'
if mood=='tired':
  print('give me food')
elif mood=='thristy':
  print('give me water')
elif mood=='bored':
  print('go on trip')
else:
  print("let's meet")

# CODE WITH MATCH CASE STATEMENT  ---improve readability
mood='worry'
match mood:
  case 'tired':
    print('let me sleep')
  case 'worry':
    print("Don't panic")
  case _:
    print('have some food')

#create a variable with integer bw 1 and 5,call it grade
num=int(input('Enter no bw 1 & 5'))
match num:
  case 1:
    print('E grade')
  case 2:
    print('D grade')
  case 3:
    print('C grade')
  case 4:
    print('B grade')
  case 5:
    print('A grade')

#create a match case statement that writes 'very good' when grade is 1 and 'very bad' when grade is 5( all other cases in between)
num=int(input('Enter no bw 1 & 5'))
match num:
  case 1:
    print('Very Good')
  case 2:
    print('Good')
  case 3:
    print('Can be Better')
  case 4:
    print('Below Avg')
  case 5:
    print('Very Bad')

#FOR LOOP
for i in range(6):
  print(i+1)

i=8
while i>0:
  print(i)
  i =i-1

# ELSE WITH WHILE LOOP
i=int(input('enter no'))
while i>0:
  print(i)
  i =i-1
else:
  print('not req')

for a in range(6):
  if a==3:
    print(a)
    break

print('How are you \nand what are you doing')

print("one two one two one \"two one\"\n two one two one two")

fruitname='apple'
len(fruitname)

fruitname[-4:-1]

#create a match case statement
num=int(input('Enter no'))
match num:
  case 1:
    print('Very Good')
  case 2:
    print('Good')
  case _:
    print('Avg')

for i in range(6):
  print(i)

for j in range(1,7):
  print(j+1)

x=1
while x<5:
  print(x)
  x=x+1

for a in range(11):
  if a==4:
    break
  print('3X',(a+1),'=',3*(a+1))

for x in range(23):
  if x==11:
    break
  print('4+',x,'=',4+x)

for x in range(23):
  if x==11:
    continue
  print('4+',x,'=',4+x)

for a in range(11):
  if a==4:
    continue
  print('3X',(a+1),'=',3*(a+1))

