# -*- coding: utf-8 -*-
"""Questions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4BQbdM6uXmHO0DAKOfJ7Yl18vWMRn9f
"""

#Wap to add all no in alist
x=[2,6,7,3.4,-5]
y=0
for i in x:
  y=y+i
print(y)

#Wap to print no from -1 to 10
x=-1
while x<11:
  print(x)
  x=x+1

for i in range(-1,11):
  print(i)

#Wap to print no from -1 to -10
x=-1
while x>-11:
  print(x)
  x=x-1

for i in range(-1,-11,-1):
  print(i)

#Wap to print no from -1 to 10
x=-1
while x<11:
  print(x)
  x=x+1

for i in range(-1,11):
  print(i)

#Even no from 1 to 20
for no in range(1,21):
 if no%2==0:
  print(no)

#Count Odd no from 1 to 20
count=0
for i in range(1,21):
  if i%2!=0:
    count=count+1
    print(i)
print('count',count)

#Wap to check a string is reversed or not
a='nitin'
b=''
for i in a:
  b=i+b
print(b)
if a==b:
    print('reversed')
else:
    print('not reversed')

#Wap to check a string is palindrome or not
a='nitin'
b=''
for i in a:
  b=i+b
print(b)
if a==b:
    print('palindrome')
else:
    print('np')

#Print first n natural no in reverse order
n=int(input('enter no'))
i=n
while i>0:
  print(i)
  i=i-1

# Sum of first n natural no
  n=int(input('enter no upto which you want to add'))
  i=1
  sum=0
  while i<=n:
    sum=sum+i
    i=i+1
  print('sum is',sum)

# Program to print sum of square from 1 to n
n=int(input('enter no upto which you want to add'))
i=1
sum =0
while i<=n:
  sq=i*i
  sum =sum +sq
  i=i+1
print('squared sum is',sum)

#Print even no from 1 to n
n=int(input('enter no'))
count=0
for i in range(1,n):
  if i%2==0:
    count=count+1
    print(i)
print('count even',count)

#Sum of even no from 1 to n
n=int(input('enter no'))
sum=0
for i in range(1,n):
  if i%2==0:
    sum=sum+i
    print(i)
print('sum is',sum)

#Find sum of digits of a given no
a=int(input('enter no'))
sum=0
while a>0:
  sum=sum+(a%10)
  a=a//10
print('sum is',sum)

# Sum of square of digits of a no
a=int(input('enter no'))
sum=0
while a>0:
      sum=sum+(a%10)*(a%10)
      a=a//10
print('sum is',sum)

# Check if given (3 digit no) no is armstrong or not
x=int(input('enter no'))
initial=x
sum=0
while x>0:
      sum=sum+(x%10)*(x%10)*(x%10)
      x=x//10
print('sum is',sum)
if sum==initial:
   print(initial ,'is armstrong')
else:
   print('not armstrong')

# Check if given no is armstrong or not
z=int(input('enter no'))
i=z
count=0
while i>0:
  i=i//10
  count=count+1
i=z
sum=0
while i>0:
    digit=i%10
    x=1
    pro=1
    while x<=count:
      pro=pro*digit
      x=x+1
    sum=sum+pro
    i=i//10
if sum==z:
  print(z,'is armstg')
else:
  print('not armstg')

# Product of digit of given no
r=int(input('enter no'))
prod=1
while r>0:
  prod=prod*(r%10)
  r=r//10
print('prod is',prod)

#Find sum of even digits and product of odd digits of a no
n=int(input('enter no'))
sum=0
prodt=1
i=n
while i>0:
  digit=i%10
  i=i//10
  print('digits are',digit)
  if digit%2==0:
    sum=sum+digit
  else:
    prodt=prodt*digit
print('prodt is',prodt)
print('sum is',sum)

#Reverse of a no
n=int(input('enter no'))
i=n
rev_num=0
while i>0:
  digit=i%10
  rev_num=(rev_num*10)+digit
  i=i//10
print('rev_num is',rev_num)

#Check no is palindrome or not
n=int(input('enter no'))
i=n
rev_num=0
while i>0:
  digit=i%10
  rev_num=(rev_num*10)+digit
  i=i//10
print('rev_num is',rev_num)
if n==rev_num:
  print('no is palin')
else:
  print('not pal')

#Program to check prime no in given interval     (to be checked again)
lower=int(input('enter starting no'))
upper=int(input('enter ending no'))
for num in range(lower,upper+1):
  if num>1:
    for i in range(2,num):
      if (num%i)==0:
        break
    else:
      print('prime no are',num)

#Program to check if no is prime or not          (to be checked again)
no=int(input('enter no'))
if no>1:
  for i in range(2,no):
    if (no%i)==0:
      break
  else:
    print('prime')

# LCM program
a1=int(input('enter no1'))
a2=int(input('enter no2'))
if a1>a2:
  greater=a1
else:
  greater=a2
while True:
  if (greater%a1)==0 and (greater%a2)==0:
    lcm=greater
    break
  greater=greater+1
print('lcm is',greater)

# list1=[2,5,8] calculate list1*2?
list1=[2,5,8]
for i in list1:
  r=i*2
  print(r)

# Avg of no in list
y=int(input('enter no of elements you want to add in list'))
x=[]
for i in range(y):
  ele=int(input('enter no'))
  x.append(ele)
print(x)
f=0
for j in x:
  f=f+j
  avg=f/y
print('avg is',avg)

#Profit loss programme
sp=80
cp=101
x=sp-cp
if x>0:
  print('profit is',x)
elif x<0:
  print('loss is',cp-sp)
else:
  print('no profit no loss')

# calculate SI
# P=2000, R=12% , T=2yr
p=2000
r=12
t=2
si=(p*r*t)/100
a=p+si
print('amount is',a)

#calculate CI P=1000,R=10%,t=3yr
p=1000
r=10
t=3
ci=p*(pow(1+(r/100),t))
a=p+ci
print('ci is',ci)
print('amount is',a)

#Check for leap year
y=int(input('enter year'))
if y%4==0:
  print('may be leap yr')
  if y%100==0:
    print('century yr')
    if y%400==0:
      print('leap yr')
    else:
      print('not')
  else:
    print('leap yr and not century yr')
else:
  print('no leap yr')

