# -*- coding: utf-8 -*-
"""STRING SLICING.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxiVtYtYAlGuiN40ERXIRQbWh70zUDVP
"""

#ARITHMETIC OPERATOR
a=3
b=4
print('value of a+b is',a+b)

a=3
b=4
print('value of a-b is',a-b)

a=3
b=4
print('value of a*b is',a*b)

a=3
b=4
print('value of a/b is',a/b)

a=3
b=4
print('value of a//b is',a//b)

a=3
b=4
print('value of a%b is',a%b)

#ASSIGNMENT OPERATOR- +,-= ,-= ,*= ,/= etc
a=3
a+=2
print(a)

a=a+2
print(a)

#COMPARISON OPERATOR
x=(12==4)
print(x)

x=(12>=4)
print(x)

x=(12<=4)
print(x)

x=(12==4)
print(x)

x=(12>4)
print(x)

x=(12<4)
print(x)

x=(12!=4)
print(x)

#LOGICAL OPERATOR ---- and ,or, not

a='guhdih7823'
print(type(a))

#wap to add 2 nos
a=4
b=5
print(a+b)

#wap to find remainder when a no is divided by 2
x=3
a=x%2
print(a)

#Check the type of variable assigned using input func
a=input('enter data')
print(type(a))

#Use comparison operator to find out whether a given variable 'a' is greater than b or not
a=34
b=80
if a>b:
  print('a is greater than b')
else:
  print('a is either less or equal to b')

a='himanshu'
print(a)
print(type(a))

a="himanshu's"
print(a)
print(type(a))

a='''himanshu's'''
print(a)
print(type(a))

name='himanshu'
print(name[2])

print(name[1:6])

print(name[:5])

print(name[3:])

print(name[1:5])

print(name[-7:-3])

print(name[1:7:2])

print(name[0::4])

