# -*- coding: utf-8 -*-
"""STRING FUNC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEEajIpb23FXjF4C8wyCva_eyxD6tZlF
"""

Story='''Tenali Raman was once walking along a forest path when he was stopped by a merchant.'''
print(len(Story))

print(Story.replace('walking','going through'))

print(Story.find('was'))

print(Story.replace('Tenali','CV'))

story='Ajay is good in all extracurricular activ\\ities \ninfact, \t managing all events also'
print(story)

#Wap to display user entered name followed by good night using input function
name=input('enter name\n')
print('Good night '+name)

#Wap a program to fill in a letter template given with name and date
letter='''DEAR <|NAME|>,
Greetings ,On basis of Interview held with you,
I would to tell you that
you are selected!
<|DATE|>'''
name=input('Enter your name\n')
date=input('Enter date\n')
letter=letter.replace("<|NAME|>",name)
letter=letter.replace("<|DATE|>",date)
print(letter)

#Wap to find string with double spaces
st="This is a string with double  spaces"
doublespaces=st.find("  ")
print(doublespaces)

#Wap to replace string with double spaces to single space
st="This is a string with double  spaces"
st=st.replace("  "," ")
print(st)

#Wap to format following letter using escaoe sequece character
letter='Dear Hem! Today weather is very awesome so what are the nearby '
formatted_letter='Dear Hem!\n\t Today weather is very awesome so what are the nearby'
print(formatted_letter)

